### ISSUE TITLE
[Question] Data only renderer

### ISSUE THREAD

**Issue by eadf** [dcchut/dcc-lsystem#12]
I've implemented a [trivial  data only renderer ](https://github.com/eadf/dcc-lsystem/tree/optional_image) for this library.

It is intended for use cases when no image generation is required, just the raw coordinates.
It also feature gates the image generation code, so the list of dependencies is shorter.

My question is if this is something you like to incorporate into the main lib? I could make a PR if you like.

**Comment by dcchut** [comment]
Oh that's a great idea - I'd definitely welcome a PR along these lines!
