### ISSUE TITLE
[Question] Drunken dragons?

### ISSUE THREAD

**Issue by eadf** [dcchut/dcc-lsystem#17]
I've been playing around with lexical parsers lately and came up with a text parser for the TurtleLSystemBuilder.
It takes the turtle build commands as a long string (direct copy and paste from the examples) and builds the Turtle from that.

I wanted to edit the turtle parameters directly from blender, and this is what I came up with.

Is this something you want to add to dcc-lsystem? 
I could make a PR for it in a few days. It would not contain any breaking changes so it could be added mid sem-ver. It just needs one error enum added (ParseError or something). Current version uses the "logos" crate, but all that can be feature gated as usual.

![skew cantor](https://raw.githubusercontent.com/eadf/toxicblend.rs/main/img/Custom_turtle.png)

Edit: https://github.com/eadf/toxicblend.rs/blob/main/src/cmd_lsystems.rs line 318 or so..

**Comment by dcchut** [comment]
I think parsing something like this might be a bit far afield of what I had in mind for this crate.  A (potential) alternative would be to define a serde serialization/deserialize impl for the `LSystem` struct.  I believe this would cover your use case (correct me if I'm wrong) and is something I'd be happy to include.

**Comment by eadf** [comment]
My parser solves the problem of converting plain text (user input) into a LSystem turtle. A serde impl does not cover any of that.
